import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { SiteNav, SiteFooter } from "./components/layout";
import { LanguageProvider } from "./contexts/LanguageContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // optional but useful
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "bEasy Cambodia: Cleaning & Pest",
  description: "Generated by create next app",
  icons: [
    // keep a default favicon reference if present (older browsers)
    { rel: "icon", url: "/favicon.ico" },
    // explicit PNG + WebP icons (cache-busted with a version query to force refresh)
    {
      rel: "icon",
      type: "image/png",
      sizes: "32x32",
      url: "/images/Browser_logo.png?v=2",
    },
    { rel: "icon", type: "image/webp", url: "/images/Browser_logo.webp?v=2" },
    // Apple touch icon for iOS home screen
    {
      rel: "apple-touch-icon",
      sizes: "180x180",
      url: "/images/Browser_logo.png?v=2",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <LanguageProvider>
          <SiteNav />
          {children}
          <SiteFooter />
        </LanguageProvider>
      </body>
    </html>
  );
}
