import type { Metadata } from "next";
import React, { Suspense } from "react";
import TelegramChatButton from "@/app/components/TelegramChatButton";
import AnalyticsProviderClient from "@/app/components/AnalyticsProviderClient";
import { LanguageProvider } from "../contexts/LanguageContext";
import { SiteFooter, SiteNav } from "../components/layout";

export const metadata: Metadata = {
  title: "bEasy Cambodia: Cleaning & Pest",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/images/Browser_logo.png", sizes: "64x64", type: "image/png" },
    ],
    apple: "/images/Browser_logo.png",
    shortcut: "/images/Browser_logo.png",
  },
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "km" }, { lang: "zh" }];
}

interface LangLayoutProps {
  children: React.ReactNode;
  // `params` can be a plain object or a Promise resolving to the object
  // depending on how Next infers types for dynamic layouts. Accept both to
  // satisfy the compiler's union mismatch.
  params: { lang: string } | Promise<{ lang: string }>;
}

// This layout doesn't use any `await`, so keep it synchronous to match Next.js
// Layout types which expect a Component returning `ReactNode` (not `Promise`).
export default function LangLayout({ children, params }: LangLayoutProps) {
  // `params` may be a Promise at the type level; at runtime Next provides the
  // plain object. Cast to `any` to access `.lang` without forcing the layout
  // to become `async` (which would change the return type to Promise<Element>).
  const lang = (params as any)?.lang ?? "en";
  const fontWrapperClass = lang === "km" ? "font-kantumruy" : "font-inter";

  return (
    <LanguageProvider>
      <div className={fontWrapperClass}>
        <SiteNav />
        <>
          {children}
          {/* Analytics provider records UTM/referrer and emits page_view events */}
          <Suspense fallback={null}>
            <AnalyticsProviderClient />
          </Suspense>
          {/* Telegram chat widget (client-only) */}
          <TelegramChatButton />
        </>
        <SiteFooter />
      </div>
    </LanguageProvider>
  );
}

// add
