import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "bEasy Cambodia: Cleaning & Pest",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/images/Browser_logo.png", sizes: "64x64", type: "image/png" },
    ],
    apple: "/images/Browser_logo.png",
    shortcut: "/images/Browser_logo.png",
  },
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "km" }, { lang: "zh" }];
}

export default async function LangLayout(props: unknown) {
  const { children } = props as { children: React.ReactNode };
  return <>{children}</>;
}

// add
