import type { Metadata } from "next";
import TelegramChatButton from "@/app/components/TelegramChatButton";
import { LanguageProvider } from "../contexts/LanguageContext";
import { SiteFooter, SiteNav } from "../components/layout";

export const metadata: Metadata = {
  title: "bEasy Cambodia: Cleaning & Pest",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/images/Browser_logo.png", sizes: "64x64", type: "image/png" },
    ],
    apple: "/images/Browser_logo.png",
    shortcut: "/images/Browser_logo.png",
  },
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "km" }, { lang: "zh" }];
}

export default async function LangLayout(props: unknown) {
  const { children } = props as { children: React.ReactNode };
  return (
      <LanguageProvider>
        <SiteNav />
          <>
          {children}
          {/* Telegram chat widget (client-only) */}
          <TelegramChatButton />
          </>
        <SiteFooter />
      </LanguageProvider> 
  );
}

// add
